models.py
#
# saved for usage in the future
# nothing to do with database yet
#


from . import db

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_caching import Cache

bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
cache=Cache()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    cache.init_app(app,config={'CACHE_TYPE': 'simple'})

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)

    # bluePrint registed home and
    from .main import main as main_blueprint
    from .explorer import explorer as explorer_blueprint 
    app.register_blueprint(main_blueprint,url_prefix="")
    app.register_blueprint(explorer_blueprint,url_prefix="/explorer")

    app.config['TEMPLATES_AUTO_RELOAD'] = True

    return app

app/explorer/__init__.py
from flask import Blueprint

explorer = Blueprint('explorer', __name__,template_folder='templates',static_url_path='app/explorer/static',static_folder='static')

from . import edgenceExplorer

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__,template_folder='templates',static_url_path='app/main/static',static_folder='static')

from . import views, errors

app/main/views.py
from flask import render_template, url_for, redirect
from . import main
import IP2Location
import json
from flask import jsonify
from flask import make_response

# import httplib2
# from urllib.parse import urlencode
@main.route('/')
def index():
    print(url_for('main.static', filename='1.jpg'))
    return render_template('index.html')


@main.route('/explorer')
def explorer():
    return redirect(url_for("explorer.blockexplorer"))


@main.route('/networkservice')
@main.route('/networkservice2020')
def workshop():
	return main.send_static_file('workshop/networkservice.html')


@main.route('/getServerInfoList', methods=['GET'])
def getServerInfoList():
    IP2LocObj = IP2Location.IP2Location()
    IP2LocObj.open('app/main/static/IP2LOCATION-LITE-DB5.BIN')
    # LocalIPList = ['47.111.168.213', '47.102.41.81', '47.88.63.126', '161.117.84.146', '39.97.166.176', '47.92.85.186', '45.58.54.216']
    IpReplaceDic = {'47.88.63.126':'104.156.230.107', 
                    '161.117.84.146':'103.233.82.251', 
                    '47.111.168.213':'47.92.85.186',
                    '45.58.54.216':'45.58.54.216', 
                    '39.97.166.176':'123.125.71.38', 
                    '47.92.85.186':'124.239.26.95', 
                    '47.102.41.81':'101.227.66.81'} 
    IPList = []
    file1 = open('app/main/static/ip.txt')
    for line in file1:
        IPList.append(line.strip())
    file1.close()
    
    res = []

    for ip in IPList:
        if ip in IpReplaceDic:
            ip = IpReplaceDic[ip]
        loc = IP2LocObj.get_all(ip)

        # prev format is "country_short": str(loc.country_short, encoding="utf-8")
        # error: decoding str is not supported
        info = {'country_short': loc.country_short,
                'country_long': loc.country_long,
                'region': loc.region,
                'city': loc.city,
                'latitude': loc.latitude,
                'longitude': loc.longitude}
        res.append(info)
    response = make_response(json.dumps(res))
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Methods'] = 'GET,POST'
    response.headers['Access-Control-Allow-Headers'] = 'x-requested-with,content-type'    
    resp = json.dumps(res)

    return resp

app/explorer/templates/404.jinja
<!DOCTYPE html>
{% extends "base.jinja" %}
{% block content %}
    <div class="columns is-mobile">
          <div class="column is-one-third is-offset-one-third">
            <div class="message">
              <div class="message-header errorHeader">
                  <p class="is-centered">Error!
                </p>
              </div>
              <div class="message-body">
                    <h3 class="title is-3">Sorry, there was an error in your request or the page was not found.</h3>
					<br>
                </div>
              </div>
            </div>
    </div>


{% endblock %}

app/explorer/templates/410.jinja
<!DOCTYPE html>
{% extends "base.jinja" %}
{% block content %}
    <div class="columns is-mobile">
          <div class="column is-one-third is-offset-one-third">
            <div class="message">
              <div class="message-header errorHeader">
                  <p class="is-centered">Error!
                </p>
              </div>
              <div class="message-body">
                    <h1 class="is-1">Sorry, there was an error in your request.</h1>
                </div>
              </div>
            </div>
    </div>


{% endblock %}

app/explorer/templates/500.jinja
<!DOCTYPE html>
{% extends "base.jinja" %}
{% block content %}
    <div class="columns is-mobile">
          <div class="column is-one-third is-offset-one-third">
            <div class="message">
              <div class="message-header errorHeader">
                  <p class="is-centered">Error!
                </p>
              </div>
              <div class="message-body">
                    <h1 class="is-1">Sorry, there was an error in your request.</h1>
                </div>
              </div>
            </div>
    </div>


{% endblock %}

app/explorer/templates/base.jinja
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="keywords" content="edgence, block, transaction, node map, payment id, blockexplorer, hashrate, difficulty, explorer, blockchain, edgence, txpool, blocksize">
  <meta name="description" content="A Edegence cryptocurrency block and transaction explorer.">
  <title>Edgence := Edge + Intelligence</title>

  <meta property="og:url" content="https://SITENAME.com">
  <meta property="og:type" content="website">
  <meta property="og:title" content="Edegnce cryptocurrency block explorer, charts, node map, wiki, and social data">
  <meta property="og:image" content="https://SITENAME.com/static/logo.png">
  <meta property="og:image:type" content="image/png">
  <meta property="og:image:width" content="285">
  <meta property="og:image:height" content="43">
  <meta property="og:description" content="Edgence cryptocurrency block explorer.">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@SITENAME">
  <meta name="twitter:creator" content="@SITENAME">
  <meta name="twitter:title" content="Edgence Cryptocurrency block explorer">
  <meta name="twitter:image" content="https://SITENAME.com/static/logo.png">
  <meta name="twitter:description" content="Edgence cryptocurrency block and transaction explorer.">

  <link rel="shortcut icon" href="{{ url_for('main.static',filename='favicon.jpg') }}" type="image/x-icon">
  <link rel="icon" href="{{ url_for('main.static',filename='favicon.jpg') }}" type="iamge/x-icon">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.3.1/css/bulma.min.css">
  <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
  <style type="text/css">
    body, html {
      font-family: "PT Sans",-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
    }
    pre {
      white-space: pre-line !important;
      width: auto !important;
    }
    .tag.is-dark {
        background-color: #757575;
        color: #fafafa;
    }
    .divTable{
        display: table;
        width: 100%;
    }
    .divTableRow {
        display: table-row;
    }
    .divTableHeading {
        background-color: #EEE;
        display: table-header-group;
    }
    .divTableCell, .divTableHead {
        border: 0px solid #999999;
        display: table-cell;
        padding: 3px 10px;
    }
    .divTableHeading {
        background-color: #EEE;
        display: table-header-group;
        font-weight: bold;
    }
    .divTableFoot {
        background-color: #EEE;
        display: table-footer-group;
        font-weight: bold;
    }
    .divTableBody {
        display: table-row-group;
    }
    .dygraph-title { color: grey; }

    .card-header-title { color: white; }
    .txpoolHeader { color: white; background-color: #2196F3}
    .hashrateHeader { color: white; background-color: #009688}
    .blockstatsHeader { color: white; background-color: hsl(171, 100%, 41%)}
    .txcountHeader { color: white; background-color: #FF5722}
    .monoData{font-family: monospace; }
    .monoTable{font-family: monospace; }
    .monoTableClickable {font-family: monospace; cursor: pointer;}
    .errorHeader { color: white; background-color: #EF5350}

  </style>
</head>
<body>
  <nav class="nav has-shadow" id="top">
    <div class="container">
      <div class="nav-left">
        <a class="nav-item" href="{{ url_for('explorer.blockexplorer') }}">
           <!--Font is Comfortaa>-->
          <img src="{{ url_for('explorer.static', filename='logo.png') }}" alt="SITENAME">
        </a>
      </div>
      <span class="nav-toggle">
        <span></span>
        <span></span>
        <span></span>
      </span>
      <div class="nav-right nav-menu">
        <a class="nav-item is-tab {% if page=='index' %}is-active {% endif %}" href="{{ url_for('main.index') }}">
          Home
        </a>
        <!--<a class="nav-item is-tab {% if relpage=='blockexplorer' %}is-active {% endif %}" href="/blockexplorer/">-->
        <!--  Block Explorer-->
        <!--</a>-->
      </div>
    </div>
  </nav>
<br>
  <div class="box">
    <div class="columns">
            <div class="column"><span class="button is-outlined is-dark is-disabled is-large">Height: {{ blockstats['height'] }}</span></div>
            <div class="column"><span class="button is-outlined is-dark is-disabled is-large">Difficulty: {{ blockstats['difficulty'] }} KH/s</span></div>
            <div class="column"><span class="button is-outlined is-dark is-disabled is-large">TXPool Count: {{ blockstats['tx_pool_size'] }}</span></div>
    </div>
</div>

{% block content %}{% endblock %}
<!--box-->
 <div class="content-section-a footer">
    <div class="container">
        {# <img src="app/explorer/static/xiaohui.jpg" width=250px style="float:left;margin-right: 100px"> #}
        <img src="http://www.edgence.org/explorer/app/explorer/static/xiaohui.jpg" width=250px style="float:left;margin-right: 100px">
        <p style="font-size:200%;margin-bottom:40px;color: black"> Affiliation and Foundation </p>
        <p>● State Key Laboratory of Networking and Switching Technology</p>
        <p>&nbsp;&nbsp;&nbsp;Beijing University of Posts and Telecommunications, China</p>
        <p>● Supported by National Natural Science Foundation of China (No. 61922017)</p>
        <p>● Supported by National Key R&D Program of China (Grant No.2018YFB1004800)</p>
        <p>● Contact us: <a href="http://www.jinliangxu.com//cv/ ">Ph.D candidate Jinliang Xu</a>, <a
                href="http://www.sguangwang.com/">Prof. Shangguang Wang</a></p>
    </div>
</div>
<p align="center">Copyright © Edgence Team of BUPT. All Rights Reserved</p>


<script>
$(document).ready(function() {

  $('.submit_on_enter').keydown(function(event) {
    // enter has keyCode = 13, change it if you want to use another button
    if (event.keyCode == 13) {
      this.form.submit();
      return false;
    }
  });

});
</script>
  <script>
    (function() {
        var burger = document.querySelector('.nav-toggle');
        var menu = document.querySelector('.nav-menu');
        burger.addEventListener('click', function() {
            burger.classList.toggle('is-active');
            menu.classList.toggle('is-active');
        });
    })();
  </script>
</body>
</html>

app/explorer/templates/block.jinja
<!DOCTYPE html>
{% extends "base.jinja" %}
{% block content %}

    <div class="columns">
      <div class="column" style="overflow-x:auto;">
        <table class="table is-striped is-narrow is-bordered">
          <tbody>
        {% if blockData %}
        {% for key in blockData['block_header']|sort %}
          <tr class="monoTable"><td>{{key}}</td><td>{{ blockData['block_header'][key] }}</td></tr>
        {% endfor %}
        {% else %}
          <tr><td>Err!</td><td>Err!</td><td>Err!</td><td>Err!</td></tr>
        {% endif %}
          </tbody>
        </table>  
      </div>
    </div>

    <div class="columns">
      <div class="column" style="overflow-x:auto;">
        <table class="table is-striped is-narrow is-bordered">
          <thead>
            <tr>
              <th>Block Transactions</th>
            </tr>
          </thead>
          <tbody>
        {% if blockData %}
        {% set height= blockData['block_header']['height'] %}
        {% for key in blockData['tx_hashes'] | sort %}
          <tr onclick="window.document.location='{{ url_for('explorer.txid',txid= key ,blockHeight= height ) }} '" ; class="monoTableClickable"><td>{{key}}</td></tr>
        {% endfor %}
        {% else %}
          <tr><td>Err!</td><td>Err!</td><td>Err!</td><td>Err!</td></tr>
        {% endif %}
          </tbody>
        </table>  
      </div>
    </div>


    <script type="text/javascript">

    window.onload = function timestamp2time() {

        $('tr.monoTable:last td')[0].textContent='time';

        let temp = $('tr.monoTable:last td')[1].textContent;
        temp = moment.unix(temp);
        temp = temp.format('YYYY-MM-DD HH:mm:ss');
        $('tr.monoTable:last td')[1].textContent = temp;

    };

    </script>
{% endblock %}

app/explorer/templates/blockexplorer.jinja
<!DOCTYPE html>
{% extends "base.jinja" %}
{% block content %}
<script type="text/javascript">

$(function() {
    $('form').each(function() {
        $(this).find('input').keypress(function(e) {
            // Enter pressed?
            if(e.which == 10 || e.which == 13) {
                this.form.submit();
            }
        });

        $(this).find('input[type=submit]').hide();
    });
});


window.onload = function timestamp2time() {
  
    var list = []; 
    list = $(".timestamp");
    for (let i=0; i<list.length; i++){
      let temp = $(".timestamp")[i].textContent;
      temp = moment.unix(temp);
      temp = temp.format('YYYY-MM-DD HH:mm:ss');
      {# console.log('TS:'+$(".timestamp")[i].textContent+' '+'Format:'+temp); #}
      $(".timestamp")[i].textContent = temp;
    }

};

</script>

    <div class="columns">
      <div class="column" style="overflow-x:auto;">
       <form method='POST' action="{{url_for('explorer.expsearch')}}">
        <table class="table is-striped is-narrow">
          <thead>
            <tr>
              <th>Time(UTC)</th>
              <th>Block/Height</th>
              <th>TX Count</th>
              <th>Hash</th>
            </tr>
          </thead>
          <tbody>
        {% if blockList %}
          <tr class="monoTable control"><td></td><td ><input name="blocksearch" class="input is-small is-primary submit_on_enter" type="text" placeholder="Block# Search..." ></td></tr>
        {% for key in blockList %}
          <tr onclick="window.document.location='{{ url_for('explorer.block',block=key['block_header']['height'] ) }}';" class="monoTableClickable"><td class="timestamp">{{key['block_header']['timestamp']}}</td><td>{{ key['block_header']['height'] }}</td><td>{{ key['tx_hashes']|length }}</td><td>{{ key['block_header']['hash'] }}</td></tr>
        {% endfor %}
        {% else %}
          <tr><td>Err!</td><td>Err!</td><td>Err!</td><td>Err!</td></tr>
        {% endif %}
          </tbody>
        </table>  
       </form>
      </div>
    </div>
{% endblock %}

app/explorer/templates/txid.jinja
<!DOCTYPE html>
{% extends "base.jinja" %}
{% block content %}


<div class="columns">
  <div class="column" style="overflow-x:auto;">
    <table class="table is-striped is-narrow is-bordered">
      <thead>
        <tr>
          <th>Found in Block</th>
          <th>Hash</th>
        </tr>
      </thead>
      <tbody>
        {% if txData[0] %}
        <tr class="monoTable">
          <td><a
              href="{{ url_for('explorer.block',block= txData[0]['block_height']) }}">{{txData[0]['block_height']}}</a>
          </td>
          <td>{{txData[0]['tx_hash']}}</td>
        </tr>
        {% else %}
        <tr>
          <td>Err!</td>
          <td>Err!</td>
          <td>Err!</td>
          <td>Err!</td>
        </tr>
        {% endif %}
      </tbody>
    </table>
  </div>
</div>

<div class="columns">
  {% if txData[1] %}
  <div class="column" style="overflow-x:auto;">

    <div class="column">
      <article class="message">
        <div class="message-header">
          <p class="is-4"><b>transaction Data:</b></p>
        </div>
      </article>
    </div>
    <table class="table is-striped is-narrow">
      <thead>
        <tr>
          <th>serviceId</th>
          <th>postId</th>
          <th>actionId</th>
        </tr>
      </thead>
      <tbody>
        <tr class="monoTable">
          <td>{{ txData[1]['serviceId'] }}</td>
          <td>{{ txData[1]['postId'] }}</td>
          <td>{{ txData[1]['actionId'] }}</td>
        </tr>
      </tbody>
    </table>

    <table class="table is-striped is-narrow">
      <thead>
        <tr>
          <th>locktime</th>
        </tr>
      </thead>
      <tbody>
        <tr class="monoTable">
          <td>{{ txData[1]['locktime'] }}</td>
        </tr>
      </tbody>
    </table>

    <table  class="table is-striped is-narrow">
      <thead>
        <tr>
          <th>data</th> 
        </tr>
      </thead>
      <tbody>
        <tr class="monoTable">
          <td>{{ txData[1]['data'] }}</td>
        </tr>
      </tbody>
    </table>

    {% for name in ['txins','txouts'] %}
    <div class="column">
      <article class="message">
        <div class="message-header">
          <p class="is-4"><b>{{ name }}:</b></p>
        </div>
      </article>
    </div>
    <table class="table is-striped is-narrow">
      <thead>
        <tr>
          {% for k in txData[1][name][0] %}
          <th>{{ k }}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for baseItem in txData[1][name] %}
        <tr class="monoTable">
          {% for v in baseItem.values() %}
          <td>{{ v }}</td>
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endfor %}

  </div>
  {% else %}
  <p class="monoData">Err!</p>
  {% endif %}
</div>

{% endblock %}

app/main/templates/base.html
{% extends "bootstrap/base.html" %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

{% block title %}
Edgence := Edge + Intelligence
{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('main.static',filename='favicon.jpg') }}"
type="image/x-icon">
<link rel="icon" href="{{ url_for('main.static',filename='favicon.jpg') }}" type="iamge/x-icon">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">Edgence</a>
        </div>
        <li class="navbar-collapse collapse">

            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{ url_for('main.explorer') }}">Explorer</a></li>
                <li><a href="http://forum.edgence.org" target="view_window">Forum</a></li>
                <li><a href="https://github.com/EdgeIntelligenceChain" target="view_window">Github</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;
        </button>
    {{ message }}
    </div>
    {% endfor %}
    <!--渲染flash模块-->
    {% block page_content %}{% endblock %}
    <!--模块中的内容由衍生模板产生-->
</div>
<p align="center">Copyright © Edgence Team of BUPT. All Rights Reserved</p>
{% endblock %}

app/main/templates/masternodes.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block head %}
{{ super() }}
<meta charset="utf-8">
<!-- <script src="../static/js/echarts.js"></script>
<script src="../static/js/jquery.js"></Script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/map/js/china.js"></script>
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/map/js/world.js"></script> -->
{% endblock %}

{% block page_content %}
<h1>masternodes</h1>
<!-- <div id="main" style="width: 1200px;height:800px;"></div> -->
{% endblock %}

{% block scripts %}
{{ super() }}
<!-- 为ECharts准备一个具备大小（宽高）的Dom -->
<!-- <script type="text/javascript">
    var ipToLocation = function () {
        $.ajax({
            // url: 'http://127.0.0.1:5000/getServerInfoList',
            url: 'http://www.edgence.org/getServerInfoList',
            type: 'get',
            dataType: 'json',
            success: function (resp) {
                var data = [],
                    geoCoordMap = {},
                    location = [];
                for (let i = 0; i < resp.length; i++) {
                    // data[i] = { name: resp[i].city, value: 100 };
                    location[i] = resp[i].city;
                    geoCoordMap[resp[i].city] = [resp[i].longitude, resp[i].latitude];

                }

                var location_name = [];
                for (let i = 0; i < location.length; i++) {
                    if (location_name.indexOf(location[i]) == -1) {
                        location_name.push(location[i])
                    }
                }
                var location_count = new Array(location_name.length);
                for (let t = 0; t < location_count.length; t++) {
                    location_count[t] = 0;
                }
                for (let p = 0; p < location_name.length; p++) {
                    for (var j = 0; j < location.length; j++) {
                        if (location_name[p] == location[j]) {
                            location_count[p]++;
                        }
                    }

                }
                for (let m = 0; m < location_name.length; m++) {
                    console.log(location_name[m] + "重复的次数为：" + location_count[m]);
                    data[m] = { name: location_name[m], value: 30 * location_count[m] };
                }


                // 基于准备好的dom，初始化echarts实例
                var myChart = echarts.init(document.getElementById('main'));

                var convertData = function (data) {
                    var res = [];
                    for (var i = 0; i < data.length; i++) {
                        var geoCoord = geoCoordMap[data[i].name];
                        if (geoCoord) {
                            res.push({
                                name: data[i].name,
                                value: geoCoord.concat(data[i].value)
                            });
                        }
                    }
                    return res;
                };

                option = {
                    backgroundColor: '#404a59',
                    title: {
                        text: 'MasterNodes',
                        subtext: 'masternodes of Edgence across the world',
                        sublink: 'http://www.edgence.org',
                        left: 'center',
                        textStyle: {
                            color: '#fff'
                        }
                    },
                    tooltip: {
                        trigger: 'item'
                    },
                    legend: {
                        orient: 'vertical',
                        y: 'bottom',
                        x: 'right',
                        data: ['server'],
                        textStyle: {
                            color: '#fff'
                        }
                    },
                    geo: {
                        map: 'world',
                        label: {
                            emphasis: {
                                show: false
                            }
                        },
                        roam: true,
                        itemStyle: {
                            normal: {
                                areaColor: '#323c48',
                                borderColor: '#111'
                            },
                            emphasis: {
                                areaColor: '#2a333d'
                            }
                        }
                    },
                    series: [
                        {
                            name: 'server',
                            type: 'scatter',
                            coordinateSystem: 'geo',
                            data: convertData(data),
                            symbolSize: function (val) {
                                return val[2] / 10;
                            },
                            label: {
                                normal: {
                                    formatter: '{b}',
                                    position: 'right',
                                    show: false
                                },
                                emphasis: {
                                    show: true
                                }
                            },
                            itemStyle: {
                                normal: {
                                    color: '#ddb926'
                                }
                            }
                        },
                        {
                            name: 'Top 5',
                            type: 'effectScatter',
                            coordinateSystem: 'geo',
                            data: convertData(data.sort(function (a, b) {
                                return b.value - a.value;
                            }).slice(0, 6)),
                            symbolSize: function (val) {
                                return val[2] / 10;
                            },
                            showEffectOn: 'render',
                            rippleEffect: {
                                brushType: 'stroke'
                            },
                            hoverAnimation: true,
                            label: {
                                normal: {
                                    formatter: '{b}',
                                    position: 'right',
                                    show: true
                                }
                            },
                            itemStyle: {
                                normal: {
                                    color: '#f4e925',
                                    shadowBlur: 10,
                                    shadowColor: '#333'
                                }
                            },
                            zlevel: 1
                        }
                    ]
                };
                // 使用刚指定的配置项和数据显示图表。
                myChart.setOption(option);
            },
            error: function () {

            }
        });


    };
    ipToLocation();
</script> -->
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

{% block title %}
Edgence := Edge + Intelligence
{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static',filename='favicon.jpg') }}"
type="image/x-icon">
<link rel="icon" href="{{ url_for('static',filename='favicon.jpg') }}" type="iamge/x-icon">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">Edgence</a>
        </div>
        <li class="navbar-collapse collapse">

            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{ url_for('main.masternodes') }}">Masternodes</a></li>
                <li><a href="https://github.com/EdgeIntelligenceChain" target="view_window">Github</a></li>
                
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;
        </button>
    {{ message }}
    </div>
    {% endfor %}
    <!--渲染flash模块-->
    {% block page_content %}{% endblock %}
    <!--模块中的内容由衍生模板产生-->
</div>
<p align="center">Copyright © Edgence Team of BUPT. All Rights Reserved</p>
{% endblock %}